// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADNxLSsz7f33vP_gW0ZIfdeNTpHWLBAEY',
    appId: '1:313373988915:web:b0f8417dcdbb480979ab46',
    messagingSenderId: '313373988915',
    projectId: 'chat-app-git',
    authDomain: 'chat-app-git.firebaseapp.com',
    storageBucket: 'chat-app-git.appspot.com',
    measurementId: 'G-97MSL862L6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqVM3m64OGDGJ2-pXG_IQgDG1jnEFZyfE',
    appId: '1:313373988915:android:ee1d05ddbef6168379ab46',
    messagingSenderId: '313373988915',
    projectId: 'chat-app-git',
    storageBucket: 'chat-app-git.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBObSuJKPFfYcEW271dy0dSgjH7g74-X9k',
    appId: '1:313373988915:ios:fe992acfe28db4f779ab46',
    messagingSenderId: '313373988915',
    projectId: 'chat-app-git',
    storageBucket: 'chat-app-git.appspot.com',
    iosClientId: '313373988915-550fao4c20cktgt0ribj0o8uviv7ee8j.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBObSuJKPFfYcEW271dy0dSgjH7g74-X9k',
    appId: '1:313373988915:ios:c67ab72876356dd679ab46',
    messagingSenderId: '313373988915',
    projectId: 'chat-app-git',
    storageBucket: 'chat-app-git.appspot.com',
    iosClientId: '313373988915-8vgvl9m49se34fnmfjkkmuq2m0j53amf.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
